package com.teamsclone.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    TEAM_NOT_FOUND,
    TEAM_MEMBER_ALREADY_EXISTS,
    TEAM_MEMBER_NOT_FOUND,
    CANNOT_REMOVE_OWNER,
    CHANNEL_NOT_FOUND,
    CHANNEL_NAME_ALREADY_EXISTS,
    MESSAGE_NOT_FOUND,
    MESSAGE_EDIT_FORBIDDEN,
    REACTION_ALREADY_EXISTS,
    CONVERSATION_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    ACCESS_DENIED,
    VALIDATION_ERROR,
    FILE_NOT_FOUND,
    FILE_ACCESS_DENIED,
    MEETING_NOT_FOUND
}
